---
abstract: 'Packages the APE-Project (Ajax Push Engine) Server.'
author:
  - 'Torsten Raudssus <torsten@raudssus.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: gpl2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-APE-Server
no_index:
  directory:
    - ape-server
    - inc
    - share
    - t
requires:
  File::ShareDir: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
version: 1.000000049004
